/*********************************************************************************************************
 * @name			The name of your class or method
 * @author			Rudresh Deshpande 
 * @created			01 / 05 / 2026
 * @description		Description of your code
**********************************************************************************************************/
public with sharing class Hello {
    
    public static void testNewClassDploy(){
        System.debug('Hello, world!');
        System.debug('Deploy Test Debug');
    }
}